# Generated by Django 5.1.5 on 2025-01-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_field',
            new_name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('Female', 'female'), ('other', 'Other')], default='others', max_length=25),
        ),
    ]
