# Generated by Django 5.1.5 on 2025-01-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_rename_date_of_field_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('female', 'Female'), ('other', 'Other')], default='others', max_length=25),
        ),
    ]
