# Generated by Django 5.1.5 on 2025-03-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_project_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='project',
            name='employees_assigned',
            field=models.ManyToManyField(to='newapp.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
